# Generated by Django 5.0.3 on 2024-05-29 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buscador', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CARPETA',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('NOMBRE', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PERFIL',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('NOMBRES', models.CharField(max_length=255)),
                ('APELLIDO_PATERNO', models.CharField(max_length=255)),
                ('APELLIDO_MATERNO', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='REPOSITORIO',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('NOMBRE', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ARCHIVO',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('NOMBRE', models.CharField(max_length=255)),
                ('ID_CARPETA', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='subCarpeta', to='buscador.carpeta')),
            ],
        ),
        migrations.AddField(
            model_name='carpeta',
            name='ID_PERFIL',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='subCarpeta', to='buscador.perfil'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='ID_REPOSITORIO',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='subPerfil', to='buscador.repositorio'),
        ),
    ]
