# Generated by Django 4.2.6 on 2024-05-30 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buscador', '0002_carpeta_perfil_repositorio_archivo_carpeta_id_perfil_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='ESTADO',
            field=models.BooleanField(default=True),
        ),
    ]
