# Generated by Django 5.0.3 on 2024-05-30 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buscador', '0003_perfil_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='IMAGEN',
            field=models.ImageField(blank=True, default='images/logo-default.png', null=True, upload_to='perfiles/'),
        ),
    ]
