# Generated by Django 5.0.3 on 2024-05-30 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buscador', '0004_perfil_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivo',
            name='ARCHIVO',
            field=models.FileField(blank=True, null=True, upload_to='archivos/'),
        ),
        migrations.AlterField(
            model_name='archivo',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='carpeta',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='repositorio',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
