# Generated by Django 5.0.3 on 2024-05-30 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buscador', '0005_archivo_archivo_alter_archivo_id_alter_carpeta_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='ID_REPOSITORIO',
        ),
    ]
