# Generated by Django 5.0.3 on 2024-05-30 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buscador', '0006_remove_perfil_id_repositorio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfil',
            old_name='ESTADO',
            new_name='ACTIVO',
        ),
    ]
