# Generated by Django 5.0.3 on 2024-05-30 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buscador', '0007_rename_estado_perfil_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivo',
            name='MASIVA',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='archivo',
            name='ID_CARPETA',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subCarpeta', to='buscador.carpeta'),
        ),
    ]
