# Generated by Django 5.0.3 on 2024-06-12 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buscador', '0008_archivo_masiva_alter_archivo_id_carpeta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='IMAGEN',
            field=models.ImageField(blank=True, default='media/perfiles/logo-default.png', null=True, upload_to='perfiles/'),
        ),
    ]
