# Generated by Django 5.0.3 on 2024-06-12 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buscador', '0012_alter_perfil_fecha_contratacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='FECHA_CONTRATACION',
            field=models.DateField(),
        ),
    ]
