# Generated by Django 5.0.3 on 2024-06-12 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buscador', '0013_alter_perfil_fecha_contratacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='UNIDAD_ORGANIZATIVA',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('NOMBRE', models.CharField(default='SIN UNIDAD ORGANIZATIVA', max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='FECHA_CONTRATACION',
        ),
    ]
