# Generated by Django 5.0.3 on 2024-06-13 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buscador', '0015_alter_unidad_organizativa_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='FECHA_CONTRATACION',
            field=models.DateField(default='1900-01-01'),
        ),
    ]
