# Generated by Django 5.0.3 on 2024-06-13 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buscador', '0016_perfil_fecha_contratacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='UO_ID',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='subCarpeta', to='buscador.unidad_organizativa'),
        ),
    ]
