# Generated by Django 5.0.3 on 2024-06-17 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buscador', '0019_alter_archivo_fecha_carga'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivo',
            name='ID_CARPETA',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='archivo_set', to='buscador.carpeta'),
        ),
    ]
