# Generated by Django 5.0.3 on 2024-06-19 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buscador', '0021_plantilla'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plantilla',
            old_name='nombre',
            new_name='NOMBRE',
        ),
        migrations.AddField(
            model_name='plantilla',
            name='NOMENCLATURA',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
