# Generated by Django 5.0.3 on 2024-06-19 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buscador', '0022_rename_nombre_plantilla_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantilla',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
