# Generated by Django 5.0.3 on 2024-06-19 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buscador', '0023_alter_plantilla_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantilla',
            name='NOMENCLATURA',
            field=models.CharField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
    ]
