# Generated by Django 5.0.3 on 2024-06-21 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buscador', '0024_alter_plantilla_nomenclatura'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantilla',
            name='ACTIVO',
            field=models.BooleanField(default=True),
        ),
    ]
